package Items.Properties;

public enum Platform { MSX, PC_ENGINE, NES, SNES, N64, GAMECUBE, WII, WII_U, SWITCH, PS1, PS2, PS3, PS4, PS5, MASTER_SYSTEM,
    GENESIS, SATURN, DREAMCAST, XBOX, XBOX360, XBOX_ONE, XBOX_SERIES}
